### PR TITLE
Minor linting and doc fixes

### PR DESCRIPTION
**Pull request by nyurik**
* Addressed some clippy rules
* one minor doc cleanup (seems like there is no `SyscallRet` anywhere)

### CODE REVIEW

**Comment by nyurik** [comment]
Hmm, this is a weird one -- apparently some archs have a Sysno named `syscall`, and because of that, linter is not happy... I am not certain how much of a problem this is, will disable it for now I guess??  Note though that this is NOT a clippy lint, which makes it even stranger that it hasn't been raised before

**Comment by nyurik** [comment]
Actually, I think this can be fixed by simply renaming the fn arg to be consistent with all other ones - into `sysno`

**Comment by jasonwhite** [comment]
Strange! Looks like `syscalls::mips::Sysno::syscall` should be filtered out within the codegen.

**Comment by jasonwhite** [comment]
Thanks for the cleanup! Looks great.

**Pull request merged**
